name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    name: ci
    uses: betabitplus/ternforge-infra-ci/.github/workflows/python-library.yml@c66612f01db8fb446c63cd7178a2d22866b215ad # v3.1.0
    with:
      python-version: "3.13"
      policy-command: ""
      runtime-audit-exclude-package: "py-lib-runtime"
      playwright-browsers: ""
