name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    name: ci
    uses: betabitplus/ternforge-infra-ci/.github/workflows/python-library.yml@92ec7f62f2a949f5ea79e8feb298859a7d0e0618 # v5.5.1
    with:
      python-version: "3.13"
      runtime-audit-exclude-package: "py-lib-runtime"
      runtime-audit-ignore-vulnerabilities: ""
      playwright-browsers: ""
    secrets:
      app-private-key: ${{ secrets.TERNFORGE_SOURCE_READ_PRIVATE_KEY }}
