name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    name: ci
    uses: betabitplus/ternforge-infra-ci/.github/workflows/python-library.yml@a4c93bd10ed417c42b653f9cd5fc8d60b67df96d # v1.7.0
    with:
      python-version: "3.13"
      policy-command: ""
      runtime-audit-exclude-package: "py-lib-runtime"
