name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    uses: betabitplus/ternforge-infra-ci/.github/workflows/release.yml@c66612f01db8fb446c63cd7178a2d22866b215ad # v3.1.0
    with:
      synchronize-python-lock: true
    secrets:
      app-private-key: ${{ secrets.TERNFORGE_RELEASE_PRIVATE_KEY }}
