name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    uses: betabitplus/ternforge-infra-ci/.github/workflows/release.yml@e8ac2be1a44a5011309318f9c537eafda9bd4fad # v2.0.1
    with:
      app-client-id: ${{ vars.TERNFORGE_RELEASE_CLIENT_ID }}
      repository: ${{ github.event.repository.name }}
      release-type: python
      synchronize-python-lock: true
      dispatch-app-client-id: ${{ vars.TERNFORGE_DISPATCH_CLIENT_ID }}
    secrets:
      app-private-key: ${{ secrets.TERNFORGE_RELEASE_PRIVATE_KEY }}
      dispatch-app-private-key: ${{ secrets.TERNFORGE_DISPATCH_PRIVATE_KEY }}
