name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    uses: betabitplus/ternforge-infra-ci/.github/workflows/release.yml@088f143a4deb2529126c98691cfbbf04b56bceb8 # v3.0.0
    with:
      synchronize-python-lock: true
    secrets:
      app-private-key: ${{ secrets.TERNFORGE_RELEASE_PRIVATE_KEY }}
